name: Create and publish Docker image

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      id-token: write # Required to authenticate against AWS.
      contents: write # Required to push a tag.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Pull all the history too.

      - name: Run
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.CI_USER_TOKEN }}
        run: |
          . ./version.sh
          . ./build.sh
          . ./tag.sh

      - name: Assume deployment role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_IAM_ROLE }}
          aws-region: eu-west-1

      - name: Deploy to testing
        env:
          REPO_OWNER: {{ github.repository_owner }}
          REPO_NAME: {{ github.event.repository.name }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.CI_USER_TOKEN }}
        run: |
          ./deploy.sh
